[build]
builder = "DOCKERFILE"

[deploy]
preDeployCommand = ["bun --bun run db:migrate"]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
