[build]
builder = "DOCKERFILE"
dockerfilePath = "/Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
healthcheckPath = "/api/health"
preDeployCommand = ["bun --bun run db:migrate"]
sleepApplication = false
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 30
restartPolicyMaxRetries = 3
